name: Docker Build Check

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "client/**"
      - "server/**"
      - "docker-compose.yml"
      - "**/Dockerfile"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "client/**"
      - "server/**"
      - "docker-compose.yml"
      - "**/Dockerfile"
  workflow_dispatch:

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [client, server]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if Dockerfile exists
        run: |
          if [ ! -f "./${{ matrix.service }}/Dockerfile" ]; then
            echo "::error::Dockerfile not found at ./${{ matrix.service }}/Dockerfile"
            exit 1
          fi
          echo "✅ Dockerfile found for ${{ matrix.service }}"

      - name: Build Docker image (check only)
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64
          push: false
          tags: quickaid-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
